### ISSUE TITLE
ps3netsrv slow when 5k games

### ISSUE THREAD

**Issue by Noro944** [aldostools/webMAN-MOD#1125]
Hi, 
i recently started to use ps3netsrv with latest webman mod on my ps3 ultra slim hen. Thank you very much for the tools.
I use a cable directly connected from ps3 to pc. Speed is like 20mb/s

In ROMS folder i have in each folder 1k games
ROMS\MEGADRIVE,
ROMS\NES,
ROMS\PSPISO,
ROMS\SNES
ROMS\PSXISO(550 games because bin.cue files are listed multiple times so 550*2 =1100, i think the limit is 1200 )
So around 4-5k games, knowing that only psp/psxiso games are heavy.Others are like some mb.
I use prepiso to scan folders.

Multiple problems: 
So FIRST problem :  the scan is really really slow. Is it possible to speed it up ?
SECOND problem :  as i said above, games in ROMS\PSXISO each bin/cue files are listed so for one game i have two/multiple icons. But PSXISO which is in main folder with GAMES, PS3ISO, etc the games are correctly displayed so even if in one game folder there are like multiple bin cue files the game is listed only one time.
Thanks

**Comment by aldostools** [comment]
Thank you for your feedback. I will try to improve these issues if I get some free time this weekend.

**Comment by aldostools** [comment]
You can try this test build [LINK REMOVED]

It should fix the issue that allowed duplicated PSX games in /ROMS/PSXISO

I also added a new condition to only scan the ROMS paths listed in `/dev_hdd0/tmp/wm_res/roms_paths.txt`
You have to edit the text file after installation so it only includes the roms folders that you need to scan.
Check if the scanning time is improved.

**Comment by Noro944** [comment]
Thanks, i will try it

**Comment by Noro944** [comment]
So i have tested it, i edited roms_paths.txt. Launched the scan and it hanged at the end of scan. Tried multiple times, same result. Every time i have to restart the ps3. So something got wrong. 

Something that i have noticed: games in folder ROMS\PSPISO are scanned very fastly (30 seconds for 800 games) but SNES,NES,MEGADRIVE which contain 1k games each are scanned super slowly like 5-10 minutes each folder.
Is there a limit maybe 800 games in each folder that i have to put ?

**Comment by aldostools** [comment]
Thank you for your feedback. I will check why it's hanging... probably a segfault error due the optimization.

In regards to the difference in time between PSPISO and SNES/NES/MEGADRIVE ROMS, I don't know why it's taking 10X more time. The code executed is exactly the same. I will try to investigate.

**Comment by Noro944** [comment]
I have reverted to the stable version and got another issue: 
i have uploaded ABC Monday Night Football (USA).png in /dev_hdd0/game/BLES80608/USRDIR/covers_retro/snes
and i have the game in ROMS\SNES folder but after scan it didn't add the icon in game list. 
Is there something wrong i did ?

**Comment by aldostools** [comment]
webMAN MOD does not check the ROMS covers in multiMAN folder.
The covers for ROMS should be included in the same folder of the ROMS with the same file name (without extension) + .png or .jpg

I have fixed the last version, so it doesn't freeze (at least it didn't on my system) [webMAN_MOD_latest.zip](https://github.com/user-attachments/files/17177346/webMAN_MOD_latest.zip)

It has a few hacks to speed up the file scanning, but probably you won't see big improvements.

**Comment by Noro944** [comment]
Thank for the tip for ROMS covers.
It didn't hang after the scan, 
it does list now in ROMS\PSXISO only one game per folder 👍 
However the scan is very slow for all the folders (even for PSXISO) except PSPISO, maybe because PSPISO contains .iso files ?

**Comment by Noro944** [comment]
Can you tell me which format is the fastest to scan the games on external disk fat32 or exfat ? is external disk faster than ps3netsrv ? ( i don't think so)

**Comment by aldostools** [comment]
Can you test taking out the cue files from the folder PSXISO?

If it scans much faster, I could make wMM load the cue files from another folder when the BIN is mounted.

**Comment by aldostools** [comment]
> Can you tell me which format is the fastest to scan the games on external disk fat32 or exfat ? is external disk faster than ps3netsrv ? ( i don't think so)

External disk FAT32 could be faster due it's reading the files using the native file system. But files cannot be larger than 4GB. Therefore most PS3ISO files need to be split as .iso.0.

External exFAT or NTFS could be faster than ps3netsrv, but I haven't measured the performance to confirm it.

**Comment by Noro944** [comment]
Hi,
I have like 1.5k psxiso games so i can't remove manually cue files from game folders.
I did try fat32 drive and it's not faster. So i gave UP scanning rétro. I will only scan PS1,ps2,psp.
 And ps3 of course.
So anther thing i have found that there IS a folder named "psx" in multiman rétro folder that contains covers for ps2,PS1,psp and i have a lot of them. I will try to empty covers folders in multiman to see if the scan IS faster.
With your new version of webmanmod  should i put covers in each separate folder in multiman ?

**Comment by aldostools** [comment]
Thank you for your feedback. The covers for ROMS now are also scanned in multiMAN^s covers_retro within the folder of the same name but in lowercase.

If you have ROMS/PSXISO, it will search the covers in covers_retro/psxiso. For SNES it will use snes.

**Comment by Noro944** [comment]
Hi,
Just for information i tried the latest version 1.47.47 and with fat 32 drive at the scan ps3 hangs but the 1.47.46h works great.

**Comment by aldostools** [comment]
Thank you for your feedback. I don't remember to have touched any code related to FAT32. I will investigate.

**Comment by aldostools** [comment]
> Hi, Just for information i tried the latest version 1.47.47 and with fat 32 drive at the scan ps3 hangs but the 1.47.46h works great.

I tried to scanning games stored on FAT32 but unfortunately I couldn't reproduce your issue.

Maybe your issue with 1.47.47 was a random freeze that could happen ocassionally. If you could find a pattern of how to reproduce the bug, it would help identify the bug.

**Comment by Noro944** [comment]
Well, i use a 4 tb hard drive. It contains 1k games in PSXISO folder, 700 games in ROMS\PSPISO and 400 games in ROMS\PSXISO.
I tried several times to scan on 1.47.47  but each time it hanged. On 1.47.46h it does scan without problems. Maybe it's the new feature on removal of duplicates PS1 cue/bien files that hangs the system?

**Comment by aldostools** [comment]
Thank you for your feedback. The issue could be related that you're testing with 1k games which are invalid ISOs. 
Or maybe the number of games is exceeding the memory allocated.

I don't think that the removal of duplicates PS1 is affecting, because I only omitted the scanning of the CUE files to fix the issue.

**Comment by Noro944** [comment]
Hey, i have done more tests on my fat32 drive, i can confirm that 1.47.47 doesn't scan more than 231 games in PSXISO folder and after reloading xmb the ps3 crashes. I think this is a serious problem. Wierd that no one noticed it maybe not a lot of people play ps1 games on ps3.
But 1.47.46h scans well 1048 games in PSXISO folder. I am NOT talking about ROMS\PSXISO but PSXISO in main directory. 
And ISOS are valid because i tried to launch a lot of them

**Comment by aldostools** [comment]
Thank you for your feedback. I will try to reproduce that scenario in FAT32 as soon as I can. Currently I'm busy.

**Comment by aldostools** [comment]
@Noro944 Thanks to your report I found a segfault error thatt occurred during ROMS scanning. It should be fixed on 1.47.47a.

It still could be improved more, but at least it currently should support 2000 ROMS or ISOs stored in ROMS/PSXISO folder.

**Comment by Noro944** [comment]
Thanks i will give it a try this evening.

**Comment by Noro944** [comment]
I just tested it, unfortunately problem was not fixed
Folder **PSXISO** shows 231 games instead of 1070.
Folder **ROMS/PSXISO** shows 0 games instead of 433, 
only **ROMS/PSPISO** shows correct number of 699 games. After the scan ps3 hangs and stops working.

Version 1.47.46h works well, the only problem is that ROMS/PSXISO shows the same game multiple times

**Comment by aldostools** [comment]
Thank you for your feedback. Last night I tested it and it worked perfectly with +1500 games having standard memory profile selected and 4-Bg.

I will test again tonight and will let you know.

**Comment by aldostools** [comment]
Dear @Noro944 
I have re-uploaded webMAN MOD 1.47.47a with a better algorithm that shouldn't break ROMS XMLs.
You can update using the online updater on XMB menu or download & reinstall from [github releases](https://github.com/aldostools/webMAN-MOD/releases).

**Comment by Noro944** [comment]
So i have tried it,
ROMS\PSXISO and ROMS\PSPISO didn't scan so it thinks folders are empty and PSXISO only shows 231 games. So something is wrong. After the scan i choose to reload xmb and it hangs and goes to recovery screen.

**Comment by aldostools** [comment]
Thank you for your feedback. Something must be wrong on your settings or environment (hardware??).

I have scanned successfully +1500 PSX ISOs (bin) found in /dev_usb000/ROMS/PSXISO. I have repeated the test several times.

The games are real ISOs and I have included the title id in the file name to speed up the the covers detection.

**Comment by Noro944** [comment]
My ps1 games are cue/bin files and are in separate folders so each folder contains one cue file and one bin file.
Exemples:
PSXISO\2Xtreme (Europe) [SCES00400]\2Xtreme (Europe) [SCES00400].bin
PSXISO\2Xtreme (Europe) [SCES00400]\2Xtreme (Europe) [SCES00400].cue
PSXISO\40 Winks (Europe) [SLES_019.37]
and for roms
ROMS\PSXISO\Lunar - Silver Star Story Complete (USA) (The Making of) [SLUS_009.21]
ROMS\PSPISO\2D Adventures of Rotating Octopus Character, The (Europe) (minis) (PSN) [NPEZ-00363].iso

I never had problem before that new update. 1.47.46h does scan them well except ROMS/PSXISO where they are duplicated but atleast it works. So i will stick to 1.47.46h version for now.

**Comment by aldostools** [comment]
Ok. Although I don't understand how the changes made in 1.47.47 could have affected your results.

It basically ignores CUE in ROMS scanning and added the filter 'roms_paths.txt' to ignore the scanning of certain paths.
The latest build improves the memory usage in scanning.

Maybe you could try taking out some games from /dev_usb000/ROMS/PSXISO or simply move them to /dev_usb000/PSXISO to check if that makes a difference. If you don't want to waste more time in this issue, it's ok that you stick with 1.47.46h

**Comment by Noro944** [comment]
I have already tried that. It doesnt scan if there IS just ROMS\PSXISO with 450 games in my fat32 drive. And if there is just PSXISO it just scans 231 games.
Well knowing that i am on 4.89  
i may try to update latest firmware. And reinstall everythin again but i doubt that it will help. Lets wait and see if there are other users who have same problem as me.

**Comment by Noro944** [comment]
@aldostools Hi,
Thank you very much for the new updates, scan works now, doesn't hang (and is maybe faster ? i don't know for sure). 
A few regressions that i saw compared to 1.47.46h:

1)
cover is not added for ps2 games such as: 
Onimusha - Dawn of Dreams (Europe) (En,Fr,De,Es,It) (Disc 1) [SLES82038].BIN.ENC
Onimusha - Dawn of Dreams (Europe) (En,Fr,De,Es,It) (Disc 2) [SLES82039].BIN.ENC
i am pretty sure because there are 2 discs.

2)
covers for ps1 are listed for a few games maybe 100 covers for 1.5k games.

So covers for ps2 and ps1 are in folder called "psx" in multiman, after installation covers pkg (EP0001-BLES80608_00-COVERS00000RETRO.pkg)
Did you change something for the scan ? i know that covers for roms should be in seperate folders(snes, nes, etc)
should i create separate folders because in 1.47.46h almost all my 1.5k ps1 games are listed with covers

**Comment by aldostools** [comment]
Thank you for your feedback.

1-Tonight I will test why you don't get the cover for : Onimusha

2-Maybe your PSX games don't meet the new restricted format for covers. They are searched in `/dev_hdd0/game/BLES80608/USRDIR/covers_retro/psx` as usual. 
Also ROMS are searched in :
`/dev_hdd0/game/BLES80608/USRDIR/covers_retro/snes`,
`/dev_hdd0/game/BLES80608/USRDIR/covers_retro/psxiso`,
`/dev_hdd0/game/BLES80608/USRDIR/covers_retro/ps2iso`, etc.

To speed up the scanning I dropped the support for covers using title_id with extensions in lowercase (e.g. BLES12345.jpg).
Lower case extensions now are only supported for covers using full file name (e.g. FF7.jpg or MyGame.png)

So the covers using title id should be named like BLES12345.JPG, otherwise they will not be found.

**Comment by Noro944** [comment]
I see, thank you for the explanation. 
Yes, more than half of my covers have lowercase extensions and are using title id.

**Comment by Noro944** [comment]
So i have reinstalled two pkg covers that you have uploaded and now my games are listed corectly with covers, even onimusha. I guess i was using old versions that i have installed long time ago

**Comment by aldostools** [comment]
Excellent. So I guess the issue can be closed 😄
