### ISSUE TITLE
[Improvement] FPS Counter

### ISSUE THREAD

**Issue by LuanTeles** [aldostools/webMAN-MOD#1240]
Hey Aldo,

I'm still getting errors when exiting games on HEN, either a black screen or the XMB gets stuck with the wave animation.

So I ran some tests, and it seems that disabling the plugin when quitting a game and restoring it on the XMB makes everything 100% stable.

I was wondering if you or @aomsin2526 could adjust the plugin on HEN to partially unload itself while exiting the game environment, and reload a few seconds after returning to the XMB.

**Comment by aldostools** [comment]
Last night @Joonie86 and I were testing some changes in HEN to prevent the hang, but so far the tests were unsuccessful.

The issue seems to be related to dynamic fan control. Try changing to SYSCON mode or manual fan speed, to check if it solves  your issue.

**Comment by LuanTeles** [comment]
> Last night [@Joonie86](https://github.com/Joonie86) and I were testing some changes in HEN to prevent the hang, but so far the tests were unsuccessful.
> 
> The issue seems to be related to dynamic fan control. Try changing to SYSCON mode or manual fan speed, to check if it solves your issue.

I'm using manual fan speed. If I set it to dynamic, it results in a black screen, as is already known. However, even on manual mode, there's about a 70% chance it gets stuck on the wave animation while the XMB is trying to load. (I'm not using webMAN to load the plugin but boot_plugins.txt)

By the way, Aldo, is it possible to disable dynamic fan speed on HEN to avoid this issue (in case it can’t be properly fixed on HEN)?

**Comment by aldostools** [comment]
By default webMAN MOD selects the manual fan mode.

If the user changes it to dynamic mode is an user decision not mine.

**Comment by Joonie86** [comment]
@LuanTeles are you using HEN on Slim or SuperSlim? if so. 

please try following-

https://github.com/PS3Xploit/PS3HEN/blob/master/payload/modulespatch.c#L673

in this line, by default we put it to sleep for 0.63sec, try increasing it up to 1.2 sec (0x5B52E80)

**Comment by LuanTeles** [comment]
> [@LuanTeles](https://github.com/LuanTeles) are you using HEN on Slim or SuperSlim? if so.
> 
> please try following-
> 
> https://github.com/PS3Xploit/PS3HEN/blob/master/payload/modulespatch.c#L673
> 
> in this line, by default we put it to sleep for 0.63sec, try increasing it up to 1.2 sec (0x5B52E80)

When I get home, I'll test it. Thanks! I'm on a SLIM.

By the way, there's been an issue with HEN for years: if an SSD is installed, only one plugin can be loaded via boot_plugins.txt, otherwise the browser won't close and will eventually crash. It might be a timing issue, since setting the plugins to load with a delay using a webMAN script works just fine.

**Comment by LuanTeles** [comment]
> > [@LuanTeles](https://github.com/LuanTeles) are you using HEN on Slim or SuperSlim? if so.
> > please try following-
> > https://github.com/PS3Xploit/PS3HEN/blob/master/payload/modulespatch.c#L673
> > in this line, by default we put it to sleep for 0.63sec, try increasing it up to 1.2 sec (0x5B52E80)
> 
> When I get home, I'll test it. Thanks! I'm on a SLIM.
> 
> By the way, there's been an issue with HEN for years: if an SSD is installed, only one plugin can be loaded via boot_plugins.txt, otherwise the browser won't close and will eventually crash. It might be a timing issue, since setting the plugins to load with a delay using a webMAN script works just fine.

I went straight to 1.2 sec

First attempt:
I loaded the fps_counter plugin and tried launching a game. The system hung on the spinning clock (this happens sometimes, possibly related to the map_paths I'm using), but it's very common when enabling the FPS counter here.

https://github.com/user-attachments/assets/1d9471a9-0665-43a0-9ef4-5f9188e74080



Second attempt:
The app booted, but the screen remained black.

Third attempt:
When exiting the game, the system hung on the XMB waves.

https://github.com/user-attachments/assets/0802f854-4b4e-452e-8371-381eadf69506

Forth Attempt:

App booted and exited just fine after removing my remaps

Edit:
I tried to reboot the system via webMAN and the system became unresponsive, so even without the remaps, is still having some issues

Fifth attempt:

Everything working good

So the problem here lies in the combination of REMAPS and the FPS counter. What could be the solution?


Sixth attempt:
I started testing individual REMAPS to see which one conflicts with the FPS counter on HEN.
Turns out the issue is likely with explorer_plugin.sprx.


Conclusion:

FPS Counter + explorer_plugin remap = issues while loading the XMB again when exiting the game.

**Comment by LuanTeles** [comment]
It's pretty stable now without the explorer_plugin remap, and I think the default HEN with the 1.2 sec delay should be fixed too.

I tried launching/exiting games for minutes and not a single crash

but I’m not sure if it’s worth removing it just for the FPS counter.
Of course, HEN is now more stable overall, but removing this remap also disables the following features:

Custom “What’s New”
Custom “My Channels”
Custom PlayStation Store billboard on the Video/PSN category
Custom "Recently Played" tab with support for homebrews
File Manager with case-insensitive file handling
What's new side options
Unlock/Lock/Delete trophies from the trophy menu

Any tips, guys?

The What’s New, My Channels, Billboards, and Recently Played tabs can be patched directly via HEN. HEN used to have Devil's What’s New patch commented out, but I’ve never managed to get it working with my own URL on the payload.

The case-insensitive file manager could probably be added to HEN too, I just have no idea how, haha.

As for the trophy options, honestly, only the "delete" function is useful in practice, so I guess it can be removed without much loss.

EDIT:

I'm getting spinning clock and hang while trying to reboot via webman again ahhaha, but less less frequent

**Comment by Joonie86** [comment]
@LuanTeles "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that hanging issue still occurrs without wMM.  I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.

**Comment by LuanTeles** [comment]
> [@LuanTeles](https://github.com/LuanTeles) "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.

I was editing the post when you commented heheh

But my system hung again but as i can tell, it is now less frequent than before, or maybe it's just a placebo idk, more tests are needed.

**Comment by Joonie86** [comment]
> > [@LuanTeles](https://github.com/LuanTeles) "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.
> 
> I was editing the post when you commented heheh
> 
> But my system hung again but as i can tell, it is now less frequent than before, or maybe it's just a placebo idk, more tests are needed.

ok. after more testing... 1.2sec on NPDRM only does make things better if wMM not loaded.. so far i got no hanging. 

https://github.com/Joonie86/PS3HEN/commit/28402148c9e9270233354db82707059c1ed47a4d

^ try this fork @LuanTeles 

also testing Lite Edition of wMM.. and so far it's been stable.

**Comment by LuanTeles** [comment]
> > > [@LuanTeles](https://github.com/LuanTeles) "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.
> > 
> > 
> > I was editing the post when you commented heheh
> > But my system hung again but as i can tell, it is now less frequent than before, or maybe it's just a placebo idk, more tests are needed.
> 
> ok. after more testing... 1.2sec on NPDRM only does make things better if wMM not loaded.. so far i got no hanging.
> 
> [Joonie86/PS3HEN@2840214](https://github.com/Joonie86/PS3HEN/commit/28402148c9e9270233354db82707059c1ed47a4d)
> 
> ^ try this fork [@LuanTeles](https://github.com/LuanTeles)
> 
> also testing Lite Edition of wMM.. and so far it's been stable.

i can't compile

![Image](https://github.com/user-attachments/assets/1238cfa2-704f-440c-9831-ac68e4d6c0e4)

**Comment by Joonie86** [comment]
> > > > [@LuanTeles](https://github.com/LuanTeles) "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.
> > > 
> > > 
> > > I was editing the post when you commented heheh
> > > But my system hung again but as i can tell, it is now less frequent than before, or maybe it's just a placebo idk, more tests are needed.
> > 
> > 
> > ok. after more testing... 1.2sec on NPDRM only does make things better if wMM not loaded.. so far i got no hanging.
> > [Joonie86/PS3HEN@2840214](https://github.com/Joonie86/PS3HEN/commit/28402148c9e9270233354db82707059c1ed47a4d)
> > ^ try this fork [@LuanTeles](https://github.com/LuanTeles)
> > also testing Lite Edition of wMM.. and so far it's been stable.
> 
> i can't compile
> 
> ![Image](https://github.com/user-attachments/assets/1238cfa2-704f-440c-9831-ac68e4d6c0e4)

sorry. I just added missing struct.

https://github.com/Joonie86/PS3HEN/commit/640c71cc0673d603e8feced62e610ea63d8900f2

**Comment by LuanTeles** [comment]
> > > > > [@LuanTeles](https://github.com/LuanTeles) "HEN is more stable" does that mean that longer delay makes HEN more stable? I came to the conclusion that I get hanging in between Rebug toolbox and PKGi, PKGi is a lot more unstable.. the only homebrew that seems to be the most stable is mmCM.
> > > > 
> > > > 
> > > > I was editing the post when you commented heheh
> > > > But my system hung again but as i can tell, it is now less frequent than before, or maybe it's just a placebo idk, more tests are needed.
> > > 
> > > 
> > > ok. after more testing... 1.2sec on NPDRM only does make things better if wMM not loaded.. so far i got no hanging.
> > > [Joonie86/PS3HEN@2840214](https://github.com/Joonie86/PS3HEN/commit/28402148c9e9270233354db82707059c1ed47a4d)
> > > ^ try this fork [@LuanTeles](https://github.com/LuanTeles)
> > > also testing Lite Edition of wMM.. and so far it's been stable.
> > 
> > 
> > i can't compile
> > ![Image](https://github.com/user-attachments/assets/1238cfa2-704f-440c-9831-ac68e4d6c0e4)
> 
> sorry. I just added missing struct.
> 
> [Joonie86/PS3HEN@640c71c](https://github.com/Joonie86/PS3HEN/commit/640c71cc0673d603e8feced62e610ea63d8900f2)

Thanks it compiled

But still the same issues here with the fps counter plugin

**Comment by Joonie86** [comment]
@LuanTeles try "Disable temperature warning" on wMM,

I've been  testing FPS counter plugin while this is checked and so far it's been smooth sailing. I'm using my fork for HEN.

![Image](https://github.com/user-attachments/assets/5d436694-a37e-4b32-a4ef-f65b6dbe2736)

**Comment by LuanTeles** [comment]
> [@LuanTeles](https://github.com/LuanTeles) try "Disable temperature warning" on wMM,
> 
> I've been testing FPS counter plugin while this is checked and so far it's been smooth sailing. I'm using my fork for HEN.
> 
> ![Image](https://github.com/user-attachments/assets/5d436694-a37e-4b32-a4ef-f65b6dbe2736)

I'll test you fork tomorrow ASAP

But I successfully made my fork more stable using your changes and by removing my gameboot game_ext_patch map_path, integrating it into the payload. Now it's working 99% of the time. I took the gameboot patch from Cobra's implementation, no more spinning clock here

Now I'm just occasionally getting black screens after launching some apps, usually after exiting them a couple of times

![Image](https://github.com/user-attachments/assets/6e2617f8-3d08-4e57-afd5-0eb83caa4da5)
![Image](https://github.com/user-attachments/assets/4a1bb4ae-1998-4596-a2f5-46e45036ff2d)

**Comment by LuanTeles** [comment]
@Joonie86 When you have some free time, could you take a look at the HEN map_path? I'm wondering if it might be causing some issues on my end.

**Comment by Joonie86** [comment]
> [@Joonie86](https://github.com/Joonie86) When you have some free time, could you take a look at the HEN map_path? I'm wondering if it might be causing some issues on my end.

not sure what changes you did for map_path. for my testing I disabled all of DPRINTF for map_path because i didn't like the massive spamming.. and so far it's been running pretty well..

https://www.youtube.com/live/XU4La_L3Ojc <- check my video.

**Comment by Joonie86** [comment]
@LuanTeles 

https://github.com/PS3-4K-Pro/HEN/blob/2a4c732a8cc7f32e5c5904d2b9e367deb96a8051/files/emergency/payload/mappath.c#L855

Is there any reason why you have those two lines enabled? the official HEN doesn't use those two. L855 and L856

![Image](https://github.com/user-attachments/assets/c40135d4-4771-4667-bdd9-17f5741a13a9)

**Comment by LuanTeles** [comment]
> > [@Joonie86](https://github.com/Joonie86) When you have some free time, could you take a look at the HEN map_path? I'm wondering if it might be causing some issues on my end.
> 
> not sure what changes you did for map_path. for my testing I disabled all of DPRINTF for map_path because i didn't like the massive spamming.. and so far it's been running pretty well..
> 
> https://www.youtube.com/live/XU4La_L3Ojc <- check my video.

I meant Ben's "new" map_path. There were some issues caused by it AFAIK and i'm using lot's of mapping, see [here](https://github.com/PS3-4K-Pro/HEN/blob/master/files/normal/payload/main.c#L1397)

BTW: I just tested 10 NPDRM games with the FPS counter enabled, and everything ran smoothly.

Thank you :)

EDIT:
After a reboot I got a couple of black screen LOL hahaha and spinning clock again , tomorrow i'll test it with your fork :P

**Comment by LuanTeles** [comment]
> [@LuanTeles](https://github.com/LuanTeles)
> 
> https://github.com/PS3-4K-Pro/HEN/blob/2a4c732a8cc7f32e5c5904d2b9e367deb96a8051/files/emergency/payload/mappath.c#L855
> 
> Is there any reason why you have those two lines enabled? the official HEN doesn't use those two. L855 and L856
> 
> ![Image](https://github.com/user-attachments/assets/c40135d4-4771-4667-bdd9-17f5741a13a9)

It's for restoring the syscalls, i made a XMBML menu for that

![Image](https://github.com/user-attachments/assets/dc6557bc-b71d-49d2-bee2-d559f24deb6e)

and the check_signin is for the PSN Blocker RCO by @DeViL303

![Image](https://github.com/user-attachments/assets/efda4258-f38f-4e1d-a3ba-34fd5fd997cd)

**Comment by Joonie86** [comment]
@LuanTeles 

https://github.com/Joonie86/PS3HEN/commit/91d90274cc0c733ec5ac5548fd511d5089e2bcbf

^ further improvement on Retail game detection. and also please make sure to disable the Temperature Warnings on wMM. This fixes my hanging issue.

**Comment by aldostools** [comment]
@LuanTeles / @Joonie86 you can test the PS3HEN improvements this new build of webMAN MOD.

- I re-enabled the wait for 15 seconds before allow use fan control in-game for PS3HEN
- Added the wait also to the code that shows the "Temperature Warning" which seem to be the one causing hangs on Joonie's PS3
- Slowed down the fan control monitor to 1/3 of the times currently polled.

[webMAN_MOD_test.zip](https://github.com/user-attachments/files/20525312/webMAN_MOD_test.zip)

**Comment by LuanTeles** [comment]
I'm still having issues with the FPS counter. @Joonie86, can I send you my Pro mod with debug HEN so you can help debug it? I can't use Socat because the LAN port on my laptop is broken.

**Comment by Joonie86** [comment]
> I'm still having issues with the FPS counter. [@Joonie86](https://github.com/Joonie86), can I send you my Pro mod with debug HEN so you can help debug it? I can't use Socat because the LAN port on my laptop is broken.

Link your payload here, so far I don't have any issue with FPSCounter.

**Comment by LuanTeles** [comment]
Just lemme clean the code a bit, as the stage2 is too big to be compiled as debug

**Comment by LuanTeles** [comment]
Edit: I still can't compile due to lv2 size, i may try the original payload and then test with just my mappings.

**Comment by Joonie86** [comment]
> Edit: I still can't compile due to lv2 size, i may try the original payload and then test with just my mappings.

I do have the same problem too and I ended up commenting all of the DPRINTF on mappath .

https://github.com/PS3Xploit/PS3HEN/commit/43a9af2784b9aa664f7ab7d17b02df4af9f9d3e0

Check this one out. this works too

**Comment by LuanTeles** [comment]
I just re-based my fork from scratch, and it's much more stable now. Thanks, guys. I can finally use the FPS counter on HEN! :)

I'm having occasional issues with the No-PSN YouTube app. Sometimes when I launch it, it gets stuck on the splash screen with the FPS counter values (FPS, temps) frozen for about 3 minutes. Then after the "freeze" the app moves to the main screen, and the FPS counter starts updating again. My internet is unstable today, so that might be the cause, other than that, it's working just fine =)

BTW @Joonie86, could you check my restore_syscalls? I can only re-enable them once. For example:

If i disable the syscalls, then re-enable them,  that works fine. But if I disable them again and try to re-enable, nothing happens.

@Evilnat, if you could check this, I’d really appreciate it , I took the code from Cobra.

here's my latest src: https://github.com/PS3-4K-Pro/HEN/tree/master/files/normal


EDIT: Still having issues on my second system HAHAH i gave up

**Comment by LuanTeles** [comment]
The quality is low because I had to compress it so GitHub would allow me to upload it

https://github.com/user-attachments/assets/9c5f2997-e130-4c26-9b06-6dabd9fb337d
