### ISSUE TITLE
Colon in Foldername - Error

### ISSUE THREAD

**Issue by ghost** [aldostools/webMAN-MOD#37]
If the is a double point in the name of the gamefolder, WebMAN Fails to load that game.

**Comment by aldostools** [comment]
This issue must be already fixed in this commit
https://github.com/aldostools/webMAN-MOD/commit/a7f0556cadf925fc0b94eb9e12b808065084b971

**Comment by ghost** [comment]
Yeah but i still have this problem and I am using WebMAN 1.45.05

For example: I called the GTA Folder "[BLES] Grand Theft Auto: V" and if I try to load GTA 5 WebMAN tries to load from this Folder: "Grand Theft Auto1 V"

**Comment by ghost** [comment]
Just saw you fixed it 19 hours ago, so do I have to wait for you to release it?
