### ISSUE TITLE
1.47.33 freezes the console

### ISSUE THREAD

**Issue by Himeko7** [aldostools/webMAN-MOD#484]
After updating to 1.47.33 any action freezes the console like loading an ISO, even trying the restart function or uninstall does it. After installing 1.47.32 back it's working again. CECH-2104A

**Comment by TheCodPunch696** [comment]
I am having the same issue to everything was fine until today I tried everything I tried restoring file system, uninstalling and reinstalling, I tried uninstalling all plugins and still that issue kept happening until I tried op solution downgrading gets it working again (THANK YOU OP) but when I reupdated It was freezing again so I am keeping it on 1.47.32 can we get enlightenment on this? Thank you in advance

**Comment by aldostools** [comment]
Does it happen after using another backup manager like multiMAN or IRISIMAN?
These backup managers remove the system mappings used by webMAN, resulting in a freeze when the wm_proxy is called.

Also try installing the FULL edition that is the version that I test more.

It is recommend to disable the content scanning at start up, because the memory consumption may be high when the system starts and may cause freeze or slowdown.

**Comment by Himeko7** [comment]
> Does it happen after using another backup manager like multiMAN or IRISIMAN?

No, I do have multiman installed but rarely use it, always launch my games through webman. I literally just updated webman 
from its own menu and this started happening. Tried to also reinstall it manually uploading the pkg and the same. only got it fixed by installing the previous version.

> Also try installing the FULL edition that is the version that I test more.

Tried this also

**Comment by aldostools** [comment]
Try updating via XMB then reboot. Maybe you got a corrupted version.

Also try deleting /dev_hdd0/tmp/wm_config.bin and reboot.

I just tested it and it's mounting fine on my system Rebug 4.86.1 Lite.

**Comment by TheCodPunch696** [comment]
> Try updating via XMB then reboot. Maybe you got a corrupted version.
> 
> Also try deleting /dev_hdd0/tmp/wm_config.bin and reboot.
> 
> I just tested it and it's mounting fine on my system Rebug 4.86.1 Lite.

I seemingly have OP's issue and doing that did not fix it for me I'm on REBUG 4.84.2 D-REX 

EDIT: I also always install the Full version and multiman works fine for me.

**Comment by Himeko7** [comment]
> Try updating via XMB then reboot. Maybe you got a corrupted version.
> 
> Also try deleting /dev_hdd0/tmp/wm_config.bin and reboot.
> 
> I just tested it and it's mounting fine on my system Rebug 4.86.1 Lite.

Just tried:
- update from XML ->reboot -> test -> fail
- delete wm_config.bin -> reboot -> test -> fail

When I mount the ISO a message appears on the top right corner as usual with the path and a gamepad icon then everything is frozen still in the XML, then the power green light blinks.

Rebug 4.86.1 Lite CEX

**Comment by aldostools** [comment]
Try installing an earlier build.

I'm investigating a possible issue in the recent builds that may consuming extra memory.

**Comment by Himeko7** [comment]
> Try installing an earlier build.
> 
> I'm investigating a possible issue in the recent builds that may consuming extra memory.

Ehh that's what I did, as I mentioned a few times, 1.47.32 works fine.

**Comment by TheCodPunch696** [comment]
Yup 1.47.32 webman mod works fine for me to

**Comment by zilamo** [comment]
> 
> 
> After updating to 1.47.33 any action freezes the console like loading an ISO, even trying the restart function or uninstall does it. After installing 1.47.32 back it's working again. CECH-2104A

hi
i have same problem too

**Comment by aldostools** [comment]
Please update to 1.47.34. I have fixed a critical bug that caused a crash in the plugin.

Probably it was the reason of the freeze.

**Comment by ghost** [comment]
Updated to 4.47.34, and WebMAN is still freezing (In particular, it seems to occur when WebMAN attempts a reboot; the freezes happened to me while rebooting XMB, and when rebooting after a setting change).

**Comment by TheCodPunch696** [comment]
> Please update to 1.47.34. I have fixed a critical bug that caused a crash in the plugin.
> 
> Probably it was the reason of the freeze.

For me it seemingly fixed everything thanks a lot man :)

**Comment by aldostools** [comment]
> Updated to 1.47.34, and WebMAN is still freezing (In particular, it seems to occur when WebMAN attempts a reboot; the freezes happened to me while rebooting XMB, and when rebooting after a setting change).

Try to downgrade to 1.47.32 or lower.

**Comment by ghost** [comment]
> > Updated to 1.47.34, and WebMAN is still freezing (In particular, it seems to occur when WebMAN attempts a reboot; the freezes happened to me while rebooting XMB, and when rebooting after a setting change).
> 
> Try to downgrade to 1.47.32 or lower.

Rolled back to 1.47.32, and WebMAN no longer freezes, so I suppose the bug was introduced in 1.47.33. Wonder what's causing it?
Anyway, thanks for the help Aldo!

**Comment by Himeko7** [comment]
1.47.34 works fine for me, thanks.

**Comment by aldostools** [comment]
> > > Updated to 1.47.34, and WebMAN is still freezing (In particular, it seems to occur when WebMAN attempts a reboot; the freezes happened to me while rebooting XMB, and when rebooting after a setting change).
> > 
> > 
> > Try to downgrade to 1.47.32 or lower.
> 
> Rolled back to 1.47.32, and WebMAN no longer freezes, so I suppose the bug was introduced in 1.47.33. Wonder what's causing it?
> Anyway, thanks for the help Aldo!

Thank you for your feedback. You can give a second try to 1.47.34, many users with the issue got it fixed with that version.

If the problem persists, then rollback again to 1.47.32.

**Comment by ghost** [comment]
Alright, for some reason I'm getting freezes in 1.47.32 (after refreshing games in WebMAN). It might just be a problem on my end (unless someone else could replicate it), or a separate issue.

**Comment by aldostools** [comment]
The latest fix was related to a missing check for NULL in a primitive function "IS" that is a wrapper that compares 2 strings.

The freeze during Refresh XML list must be related to:
1- Maybe a game containing invalid characters in PARAM.SFO or in the file name.
2- Too many games to handle, which can be fixed increasing the memory usage in /setup.ps3
If you have lots of PSX games try MAX PSX+, if you have lots of PS3 try MAX PS3+. Or set [mc] to 4-bg.

It also helps to disable the scan for content at startup in /setup.ps3

**Comment by ghost** [comment]
Thanks for all the help. My freezes must be due to reason number 2: When I ripped my ninth game to my hard drive using Irisman, webman started to crash (though I thought it was just a coincidence). BTW, is there a list of valid file names for webman? Is it just the reserved characters for strings in C (like "\\"), or are there more/less restrictions?

**Comment by aldostools** [comment]
Try to use ANSI characters and numbers. Avoid special characters like <|>&+":*?\/ \\%

**Comment by Himeko7** [comment]
It may be unrelated or coincidence, but with .44 many installed pkg games don't work unless I launch a small homebrew first, just blank screen and console is frozen. FTP is still active but uploading a file results in "ERR, out of memory". Rolled back to .42 again and no issues.

**Comment by Joonie86** [comment]
No further feedback
